### ISSUE TITLE
Create Mission Text File Input

### ISSUE THREAD

**Issue by richarthurs** [Team-Guardian/guardian_guidance#4]
It would be nice to define a mission in a text file using a simple syntax such as:

wp, -122.003102, 49.23419, 25
sp, -122.003102, 49.23419, -122.01202, 49.21419, -122.023102, 49.23719, -122.023102, 49.23419, 25

Where wp and sp stand for waypoint and search pattern, and the other arguments are the waypoint location and altitude, or the list of corner points for a search pattern. Include similar syntax for defining other mission modules as well.

Make a function that parses a text file containing the mission definition (example syntax listed above). The output will be a list of mission modules created with the parameters in the file. 

This will replace createTestMission in mission.py.

**Comment by HydroAr59** [comment]
I finished it. Now I just don't know where and how I should post it.

**Comment by richarthurs** [comment]
Can you push to a new branch and then create a pull request? I'll check it out and merge if it all looks good. 

Let me know if you don't have permissions to make a new branch or anything like that. Thanks!

**Comment by richarthurs** [comment]
@HydroAr59 I have added you to the organization. Please accept the invite and push your changes to a new branch so we can do a code review and merge on Saturday. Thanks!

**Comment by richarthurs** [comment]
Fixed in #9
